// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_const_countries

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ConstCountriesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"const_countries": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"alpha2": schema.StringAttribute{
							Computed:            true,
							Description:         "country code, in two-character",
							MarkdownDescription: "country code, in two-character",
						},
						"certified": schema.BoolAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"numeric": schema.NumberAttribute{
							Computed:            true,
							Description:         "country code, ISO 3166-1 numeric",
							MarkdownDescription: "country code, ISO 3166-1 numeric",
						},
					},
					CustomType: ConstCountriesType{
						ObjectType: types.ObjectType{
							AttrTypes: ConstCountriesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type ConstCountriesModel struct {
	ConstCountries types.Set `tfsdk:"const_countries"`
}

var _ basetypes.ObjectTypable = ConstCountriesType{}

type ConstCountriesType struct {
	basetypes.ObjectType
}

func (t ConstCountriesType) Equal(o attr.Type) bool {
	other, ok := o.(ConstCountriesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConstCountriesType) String() string {
	return "ConstCountriesType"
}

func (t ConstCountriesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	alpha2Attribute, ok := attributes["alpha2"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alpha2 is missing from object`)

		return nil, diags
	}

	alpha2Val, ok := alpha2Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alpha2 expected to be basetypes.StringValue, was: %T`, alpha2Attribute))
	}

	certifiedAttribute, ok := attributes["certified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`certified is missing from object`)

		return nil, diags
	}

	certifiedVal, ok := certifiedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`certified expected to be basetypes.BoolValue, was: %T`, certifiedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	numericAttribute, ok := attributes["numeric"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`numeric is missing from object`)

		return nil, diags
	}

	numericVal, ok := numericAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`numeric expected to be basetypes.NumberValue, was: %T`, numericAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConstCountriesValue{
		Alpha2:    alpha2Val,
		Certified: certifiedVal,
		Name:      nameVal,
		Numeric:   numericVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewConstCountriesValueNull() ConstCountriesValue {
	return ConstCountriesValue{
		state: attr.ValueStateNull,
	}
}

func NewConstCountriesValueUnknown() ConstCountriesValue {
	return ConstCountriesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConstCountriesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConstCountriesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConstCountriesValue Attribute Value",
				"While creating a ConstCountriesValue value, a missing attribute value was detected. "+
					"A ConstCountriesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConstCountriesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConstCountriesValue Attribute Type",
				"While creating a ConstCountriesValue value, an invalid attribute value was detected. "+
					"A ConstCountriesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConstCountriesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConstCountriesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConstCountriesValue Attribute Value",
				"While creating a ConstCountriesValue value, an extra attribute value was detected. "+
					"A ConstCountriesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConstCountriesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConstCountriesValueUnknown(), diags
	}

	alpha2Attribute, ok := attributes["alpha2"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alpha2 is missing from object`)

		return NewConstCountriesValueUnknown(), diags
	}

	alpha2Val, ok := alpha2Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alpha2 expected to be basetypes.StringValue, was: %T`, alpha2Attribute))
	}

	certifiedAttribute, ok := attributes["certified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`certified is missing from object`)

		return NewConstCountriesValueUnknown(), diags
	}

	certifiedVal, ok := certifiedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`certified expected to be basetypes.BoolValue, was: %T`, certifiedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewConstCountriesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	numericAttribute, ok := attributes["numeric"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`numeric is missing from object`)

		return NewConstCountriesValueUnknown(), diags
	}

	numericVal, ok := numericAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`numeric expected to be basetypes.NumberValue, was: %T`, numericAttribute))
	}

	if diags.HasError() {
		return NewConstCountriesValueUnknown(), diags
	}

	return ConstCountriesValue{
		Alpha2:    alpha2Val,
		Certified: certifiedVal,
		Name:      nameVal,
		Numeric:   numericVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewConstCountriesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConstCountriesValue {
	object, diags := NewConstCountriesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConstCountriesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConstCountriesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConstCountriesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConstCountriesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConstCountriesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConstCountriesValueMust(ConstCountriesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConstCountriesType) ValueType(ctx context.Context) attr.Value {
	return ConstCountriesValue{}
}

var _ basetypes.ObjectValuable = ConstCountriesValue{}

type ConstCountriesValue struct {
	Alpha2    basetypes.StringValue `tfsdk:"alpha2"`
	Certified basetypes.BoolValue   `tfsdk:"certified"`
	Name      basetypes.StringValue `tfsdk:"name"`
	Numeric   basetypes.NumberValue `tfsdk:"numeric"`
	state     attr.ValueState
}

func (v ConstCountriesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["alpha2"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["certified"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["numeric"] = basetypes.NumberType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Alpha2.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["alpha2"] = val

		val, err = v.Certified.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["certified"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Numeric.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["numeric"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConstCountriesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConstCountriesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConstCountriesValue) String() string {
	return "ConstCountriesValue"
}

func (v ConstCountriesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"alpha2":    basetypes.StringType{},
		"certified": basetypes.BoolType{},
		"name":      basetypes.StringType{},
		"numeric":   basetypes.NumberType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"alpha2":    v.Alpha2,
			"certified": v.Certified,
			"name":      v.Name,
			"numeric":   v.Numeric,
		})

	return objVal, diags
}

func (v ConstCountriesValue) Equal(o attr.Value) bool {
	other, ok := o.(ConstCountriesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Alpha2.Equal(other.Alpha2) {
		return false
	}

	if !v.Certified.Equal(other.Certified) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Numeric.Equal(other.Numeric) {
		return false
	}

	return true
}

func (v ConstCountriesValue) Type(ctx context.Context) attr.Type {
	return ConstCountriesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConstCountriesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"alpha2":    basetypes.StringType{},
		"certified": basetypes.BoolType{},
		"name":      basetypes.StringType{},
		"numeric":   basetypes.NumberType{},
	}
}
