// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_org_mxtunnel

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrgMxtunnelResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"anchor_mxtunnel_ids": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "IDs of anchor Mist Tunnels used for edge-to-edge tunnel formation",
				MarkdownDescription: "IDs of anchor Mist Tunnels used for edge-to-edge tunnel formation",
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
					listvalidator.UniqueValues(),
				},
			},
			"auto_preemption": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"day_of_week": schema.StringAttribute{
						Optional:            true,
						Description:         "Scheduled weekday for auto preemption",
						MarkdownDescription: "Scheduled weekday for auto preemption",
						Validators: []validator.String{
							stringvalidator.OneOf(
								"",
								"any",
								"fri",
								"mon",
								"sat",
								"sun",
								"thu",
								"tue",
								"wed",
							),
						},
					},
					"enabled": schema.BoolAttribute{
						Optional:            true,
						Description:         "Whether auto preemption is enabled",
						MarkdownDescription: "Whether auto preemption is enabled",
					},
					"time_of_day": schema.StringAttribute{
						Optional:            true,
						Description:         "Scheduled time of day for auto preemption",
						MarkdownDescription: "Scheduled time of day for auto preemption",
					},
				},
				CustomType: AutoPreemptionType{
					ObjectType: types.ObjectType{
						AttrTypes: AutoPreemptionValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Preemption behavior for restoring preferred tunnel peers after failover",
				MarkdownDescription: "Preemption behavior for restoring preferred tunnel peers after failover",
			},
			"hello_interval": schema.Int64Attribute{
				Optional:            true,
				Description:         "In seconds, used as heartbeat to detect if a tunnel is alive. AP will try another peer after missing N hellos specified by `hello_retries`.",
				MarkdownDescription: "In seconds, used as heartbeat to detect if a tunnel is alive. AP will try another peer after missing N hellos specified by `hello_retries`.",
				Validators: []validator.Int64{
					int64validator.Between(1, 300),
				},
			},
			"hello_retries": schema.Int64Attribute{
				Optional:            true,
				Description:         "Number of missed hello heartbeats before an AP tries another tunnel peer",
				MarkdownDescription: "Number of missed hello heartbeats before an AP tries another tunnel peer",
				Validators: []validator.Int64{
					int64validator.Between(2, 30),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the Mist Tunnel",
				MarkdownDescription: "Unique identifier of the Mist Tunnel",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"ipsec": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"dns_servers": schema.ListAttribute{
						ElementType:         types.StringType,
						Optional:            true,
						Description:         "Name server addresses advertised for IPsec tunnel clients",
						MarkdownDescription: "Name server addresses advertised for IPsec tunnel clients",
						Validators: []validator.List{
							listvalidator.SizeAtLeast(1),
						},
					},
					"dns_suffix": schema.ListAttribute{
						ElementType:         types.StringType,
						Optional:            true,
						Description:         "Search suffixes advertised for IPsec tunnel clients",
						MarkdownDescription: "Search suffixes advertised for IPsec tunnel clients",
						Validators: []validator.List{
							listvalidator.SizeAtLeast(1),
						},
					},
					"enabled": schema.BoolAttribute{
						Optional:            true,
						Description:         "Whether IPsec support is enabled for this Mist Tunnel",
						MarkdownDescription: "Whether IPsec support is enabled for this Mist Tunnel",
					},
					"extra_routes": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"dest": schema.StringAttribute{
									Optional:            true,
									Description:         "Route destination CIDR for the IPsec extra route",
									MarkdownDescription: "Route destination CIDR for the IPsec extra route",
								},
								"next_hop": schema.StringAttribute{
									Optional:            true,
									Description:         "Route next-hop IPv4 address for the IPsec extra route",
									MarkdownDescription: "Route next-hop IPv4 address for the IPsec extra route",
								},
							},
							CustomType: ExtraRoutesType{
								ObjectType: types.ObjectType{
									AttrTypes: ExtraRoutesValue{}.AttributeTypes(ctx),
								},
							},
						},
						Optional:            true,
						Description:         "Additional routes advertised for the IPsec tunnel",
						MarkdownDescription: "Additional routes advertised for the IPsec tunnel",
					},
					"split_tunnel": schema.BoolAttribute{
						Optional:            true,
						Description:         "Whether split tunneling is enabled for IPsec clients",
						MarkdownDescription: "Whether split tunneling is enabled for IPsec clients",
					},
					"use_mxedge": schema.BoolAttribute{
						Optional:            true,
						Description:         "Whether IPsec termination uses Mist Edge",
						MarkdownDescription: "Whether IPsec termination uses Mist Edge",
					},
				},
				CustomType: IpsecType{
					ObjectType: types.ObjectType{
						AttrTypes: IpsecValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Security settings for IPsec support on this Mist Tunnel",
				MarkdownDescription: "Security settings for IPsec support on this Mist Tunnel",
			},
			"mtu": schema.Int64Attribute{
				Optional:            true,
				Description:         "0 to enable PMTU, 552-1500 to start PMTU with a lower MTU",
				MarkdownDescription: "0 to enable PMTU, 552-1500 to start PMTU with a lower MTU",
				Validators: []validator.Int64{
					int64validator.Between(0, 1500),
				},
			},
			"mxcluster_ids": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Mist Edge cluster IDs that host this Mist Tunnel",
				MarkdownDescription: "Mist Edge cluster IDs that host this Mist Tunnel",
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
					listvalidator.UniqueValues(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Display name of the Mist Tunnel",
				MarkdownDescription: "Display name of the Mist Tunnel",
			},
			"org_id": schema.StringAttribute{
				Required:            true,
				Description:         "Identifier of the org that owns the Mist Tunnel",
				MarkdownDescription: "Identifier of the org that owns the Mist Tunnel",
			},
			"protocol": schema.StringAttribute{
				Optional:            true,
				Description:         "Encapsulation protocol used for the Mist Tunnel",
				MarkdownDescription: "Encapsulation protocol used for the Mist Tunnel",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"",
						"ip",
						"udp",
					),
				},
			},
			"vlan_ids": schema.ListAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Description:         "List of VLAN IDs carried by this Mist Tunnel",
				MarkdownDescription: "List of VLAN IDs carried by this Mist Tunnel",
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
				},
			},
		},
	}
}

type OrgMxtunnelModel struct {
	AnchorMxtunnelIds types.List          `tfsdk:"anchor_mxtunnel_ids"`
	AutoPreemption    AutoPreemptionValue `tfsdk:"auto_preemption"`
	HelloInterval     types.Int64         `tfsdk:"hello_interval"`
	HelloRetries      types.Int64         `tfsdk:"hello_retries"`
	Id                types.String        `tfsdk:"id"`
	Ipsec             IpsecValue          `tfsdk:"ipsec"`
	Mtu               types.Int64         `tfsdk:"mtu"`
	MxclusterIds      types.List          `tfsdk:"mxcluster_ids"`
	Name              types.String        `tfsdk:"name"`
	OrgId             types.String        `tfsdk:"org_id"`
	Protocol          types.String        `tfsdk:"protocol"`
	VlanIds           types.List          `tfsdk:"vlan_ids"`
}

var _ basetypes.ObjectTypable = AutoPreemptionType{}

type AutoPreemptionType struct {
	basetypes.ObjectType
}

func (t AutoPreemptionType) Equal(o attr.Type) bool {
	other, ok := o.(AutoPreemptionType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AutoPreemptionType) String() string {
	return "AutoPreemptionType"
}

func (t AutoPreemptionType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	dayOfWeekAttribute, ok := attributes["day_of_week"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`day_of_week is missing from object`)

		return nil, diags
	}

	dayOfWeekVal, ok := dayOfWeekAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`day_of_week expected to be basetypes.StringValue, was: %T`, dayOfWeekAttribute))
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return nil, diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	timeOfDayAttribute, ok := attributes["time_of_day"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`time_of_day is missing from object`)

		return nil, diags
	}

	timeOfDayVal, ok := timeOfDayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`time_of_day expected to be basetypes.StringValue, was: %T`, timeOfDayAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AutoPreemptionValue{
		DayOfWeek: dayOfWeekVal,
		Enabled:   enabledVal,
		TimeOfDay: timeOfDayVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewAutoPreemptionValueNull() AutoPreemptionValue {
	return AutoPreemptionValue{
		state: attr.ValueStateNull,
	}
}

func NewAutoPreemptionValueUnknown() AutoPreemptionValue {
	return AutoPreemptionValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAutoPreemptionValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AutoPreemptionValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AutoPreemptionValue Attribute Value",
				"While creating a AutoPreemptionValue value, a missing attribute value was detected. "+
					"A AutoPreemptionValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AutoPreemptionValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AutoPreemptionValue Attribute Type",
				"While creating a AutoPreemptionValue value, an invalid attribute value was detected. "+
					"A AutoPreemptionValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AutoPreemptionValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AutoPreemptionValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AutoPreemptionValue Attribute Value",
				"While creating a AutoPreemptionValue value, an extra attribute value was detected. "+
					"A AutoPreemptionValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AutoPreemptionValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAutoPreemptionValueUnknown(), diags
	}

	dayOfWeekAttribute, ok := attributes["day_of_week"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`day_of_week is missing from object`)

		return NewAutoPreemptionValueUnknown(), diags
	}

	dayOfWeekVal, ok := dayOfWeekAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`day_of_week expected to be basetypes.StringValue, was: %T`, dayOfWeekAttribute))
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return NewAutoPreemptionValueUnknown(), diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	timeOfDayAttribute, ok := attributes["time_of_day"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`time_of_day is missing from object`)

		return NewAutoPreemptionValueUnknown(), diags
	}

	timeOfDayVal, ok := timeOfDayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`time_of_day expected to be basetypes.StringValue, was: %T`, timeOfDayAttribute))
	}

	if diags.HasError() {
		return NewAutoPreemptionValueUnknown(), diags
	}

	return AutoPreemptionValue{
		DayOfWeek: dayOfWeekVal,
		Enabled:   enabledVal,
		TimeOfDay: timeOfDayVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewAutoPreemptionValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AutoPreemptionValue {
	object, diags := NewAutoPreemptionValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAutoPreemptionValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AutoPreemptionType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAutoPreemptionValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAutoPreemptionValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAutoPreemptionValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAutoPreemptionValueMust(AutoPreemptionValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AutoPreemptionType) ValueType(ctx context.Context) attr.Value {
	return AutoPreemptionValue{}
}

var _ basetypes.ObjectValuable = AutoPreemptionValue{}

type AutoPreemptionValue struct {
	DayOfWeek basetypes.StringValue `tfsdk:"day_of_week"`
	Enabled   basetypes.BoolValue   `tfsdk:"enabled"`
	TimeOfDay basetypes.StringValue `tfsdk:"time_of_day"`
	state     attr.ValueState
}

func (v AutoPreemptionValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["day_of_week"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["time_of_day"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.DayOfWeek.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["day_of_week"] = val

		val, err = v.Enabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["enabled"] = val

		val, err = v.TimeOfDay.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["time_of_day"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AutoPreemptionValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AutoPreemptionValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AutoPreemptionValue) String() string {
	return "AutoPreemptionValue"
}

func (v AutoPreemptionValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"day_of_week": basetypes.StringType{},
		"enabled":     basetypes.BoolType{},
		"time_of_day": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"day_of_week": v.DayOfWeek,
			"enabled":     v.Enabled,
			"time_of_day": v.TimeOfDay,
		})

	return objVal, diags
}

func (v AutoPreemptionValue) Equal(o attr.Value) bool {
	other, ok := o.(AutoPreemptionValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DayOfWeek.Equal(other.DayOfWeek) {
		return false
	}

	if !v.Enabled.Equal(other.Enabled) {
		return false
	}

	if !v.TimeOfDay.Equal(other.TimeOfDay) {
		return false
	}

	return true
}

func (v AutoPreemptionValue) Type(ctx context.Context) attr.Type {
	return AutoPreemptionType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AutoPreemptionValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"day_of_week": basetypes.StringType{},
		"enabled":     basetypes.BoolType{},
		"time_of_day": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = IpsecType{}

type IpsecType struct {
	basetypes.ObjectType
}

func (t IpsecType) Equal(o attr.Type) bool {
	other, ok := o.(IpsecType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IpsecType) String() string {
	return "IpsecType"
}

func (t IpsecType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	dnsServersAttribute, ok := attributes["dns_servers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dns_servers is missing from object`)

		return nil, diags
	}

	dnsServersVal, ok := dnsServersAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dns_servers expected to be basetypes.ListValue, was: %T`, dnsServersAttribute))
	}

	dnsSuffixAttribute, ok := attributes["dns_suffix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dns_suffix is missing from object`)

		return nil, diags
	}

	dnsSuffixVal, ok := dnsSuffixAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dns_suffix expected to be basetypes.ListValue, was: %T`, dnsSuffixAttribute))
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return nil, diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	extraRoutesAttribute, ok := attributes["extra_routes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`extra_routes is missing from object`)

		return nil, diags
	}

	extraRoutesVal, ok := extraRoutesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`extra_routes expected to be basetypes.ListValue, was: %T`, extraRoutesAttribute))
	}

	splitTunnelAttribute, ok := attributes["split_tunnel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`split_tunnel is missing from object`)

		return nil, diags
	}

	splitTunnelVal, ok := splitTunnelAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`split_tunnel expected to be basetypes.BoolValue, was: %T`, splitTunnelAttribute))
	}

	useMxedgeAttribute, ok := attributes["use_mxedge"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use_mxedge is missing from object`)

		return nil, diags
	}

	useMxedgeVal, ok := useMxedgeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use_mxedge expected to be basetypes.BoolValue, was: %T`, useMxedgeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IpsecValue{
		DnsServers:  dnsServersVal,
		DnsSuffix:   dnsSuffixVal,
		Enabled:     enabledVal,
		ExtraRoutes: extraRoutesVal,
		SplitTunnel: splitTunnelVal,
		UseMxedge:   useMxedgeVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewIpsecValueNull() IpsecValue {
	return IpsecValue{
		state: attr.ValueStateNull,
	}
}

func NewIpsecValueUnknown() IpsecValue {
	return IpsecValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIpsecValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IpsecValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IpsecValue Attribute Value",
				"While creating a IpsecValue value, a missing attribute value was detected. "+
					"A IpsecValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpsecValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IpsecValue Attribute Type",
				"While creating a IpsecValue value, an invalid attribute value was detected. "+
					"A IpsecValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpsecValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IpsecValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IpsecValue Attribute Value",
				"While creating a IpsecValue value, an extra attribute value was detected. "+
					"A IpsecValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IpsecValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIpsecValueUnknown(), diags
	}

	dnsServersAttribute, ok := attributes["dns_servers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dns_servers is missing from object`)

		return NewIpsecValueUnknown(), diags
	}

	dnsServersVal, ok := dnsServersAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dns_servers expected to be basetypes.ListValue, was: %T`, dnsServersAttribute))
	}

	dnsSuffixAttribute, ok := attributes["dns_suffix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dns_suffix is missing from object`)

		return NewIpsecValueUnknown(), diags
	}

	dnsSuffixVal, ok := dnsSuffixAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dns_suffix expected to be basetypes.ListValue, was: %T`, dnsSuffixAttribute))
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return NewIpsecValueUnknown(), diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	extraRoutesAttribute, ok := attributes["extra_routes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`extra_routes is missing from object`)

		return NewIpsecValueUnknown(), diags
	}

	extraRoutesVal, ok := extraRoutesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`extra_routes expected to be basetypes.ListValue, was: %T`, extraRoutesAttribute))
	}

	splitTunnelAttribute, ok := attributes["split_tunnel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`split_tunnel is missing from object`)

		return NewIpsecValueUnknown(), diags
	}

	splitTunnelVal, ok := splitTunnelAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`split_tunnel expected to be basetypes.BoolValue, was: %T`, splitTunnelAttribute))
	}

	useMxedgeAttribute, ok := attributes["use_mxedge"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use_mxedge is missing from object`)

		return NewIpsecValueUnknown(), diags
	}

	useMxedgeVal, ok := useMxedgeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use_mxedge expected to be basetypes.BoolValue, was: %T`, useMxedgeAttribute))
	}

	if diags.HasError() {
		return NewIpsecValueUnknown(), diags
	}

	return IpsecValue{
		DnsServers:  dnsServersVal,
		DnsSuffix:   dnsSuffixVal,
		Enabled:     enabledVal,
		ExtraRoutes: extraRoutesVal,
		SplitTunnel: splitTunnelVal,
		UseMxedge:   useMxedgeVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewIpsecValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IpsecValue {
	object, diags := NewIpsecValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIpsecValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IpsecType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIpsecValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIpsecValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIpsecValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIpsecValueMust(IpsecValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IpsecType) ValueType(ctx context.Context) attr.Value {
	return IpsecValue{}
}

var _ basetypes.ObjectValuable = IpsecValue{}

type IpsecValue struct {
	DnsServers  basetypes.ListValue `tfsdk:"dns_servers"`
	DnsSuffix   basetypes.ListValue `tfsdk:"dns_suffix"`
	Enabled     basetypes.BoolValue `tfsdk:"enabled"`
	ExtraRoutes basetypes.ListValue `tfsdk:"extra_routes"`
	SplitTunnel basetypes.BoolValue `tfsdk:"split_tunnel"`
	UseMxedge   basetypes.BoolValue `tfsdk:"use_mxedge"`
	state       attr.ValueState
}

func (v IpsecValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["dns_servers"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["dns_suffix"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["extra_routes"] = basetypes.ListType{
		ElemType: ExtraRoutesValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["split_tunnel"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["use_mxedge"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.DnsServers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dns_servers"] = val

		val, err = v.DnsSuffix.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dns_suffix"] = val

		val, err = v.Enabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["enabled"] = val

		val, err = v.ExtraRoutes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["extra_routes"] = val

		val, err = v.SplitTunnel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["split_tunnel"] = val

		val, err = v.UseMxedge.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["use_mxedge"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IpsecValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IpsecValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IpsecValue) String() string {
	return "IpsecValue"
}

func (v IpsecValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	extraRoutes := types.ListValueMust(
		ExtraRoutesType{
			basetypes.ObjectType{
				AttrTypes: ExtraRoutesValue{}.AttributeTypes(ctx),
			},
		},
		v.ExtraRoutes.Elements(),
	)

	if v.ExtraRoutes.IsNull() {
		extraRoutes = types.ListNull(
			ExtraRoutesType{
				basetypes.ObjectType{
					AttrTypes: ExtraRoutesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.ExtraRoutes.IsUnknown() {
		extraRoutes = types.ListUnknown(
			ExtraRoutesType{
				basetypes.ObjectType{
					AttrTypes: ExtraRoutesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var dnsServersVal basetypes.ListValue
	switch {
	case v.DnsServers.IsUnknown():
		dnsServersVal = types.ListUnknown(types.StringType)
	case v.DnsServers.IsNull():
		dnsServersVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		dnsServersVal, d = types.ListValue(types.StringType, v.DnsServers.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"dns_servers": basetypes.ListType{
				ElemType: types.StringType,
			},
			"dns_suffix": basetypes.ListType{
				ElemType: types.StringType,
			},
			"enabled": basetypes.BoolType{},
			"extra_routes": basetypes.ListType{
				ElemType: ExtraRoutesValue{}.Type(ctx),
			},
			"split_tunnel": basetypes.BoolType{},
			"use_mxedge":   basetypes.BoolType{},
		}), diags
	}

	var dnsSuffixVal basetypes.ListValue
	switch {
	case v.DnsSuffix.IsUnknown():
		dnsSuffixVal = types.ListUnknown(types.StringType)
	case v.DnsSuffix.IsNull():
		dnsSuffixVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		dnsSuffixVal, d = types.ListValue(types.StringType, v.DnsSuffix.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"dns_servers": basetypes.ListType{
				ElemType: types.StringType,
			},
			"dns_suffix": basetypes.ListType{
				ElemType: types.StringType,
			},
			"enabled": basetypes.BoolType{},
			"extra_routes": basetypes.ListType{
				ElemType: ExtraRoutesValue{}.Type(ctx),
			},
			"split_tunnel": basetypes.BoolType{},
			"use_mxedge":   basetypes.BoolType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"dns_servers": basetypes.ListType{
			ElemType: types.StringType,
		},
		"dns_suffix": basetypes.ListType{
			ElemType: types.StringType,
		},
		"enabled": basetypes.BoolType{},
		"extra_routes": basetypes.ListType{
			ElemType: ExtraRoutesValue{}.Type(ctx),
		},
		"split_tunnel": basetypes.BoolType{},
		"use_mxedge":   basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"dns_servers":  dnsServersVal,
			"dns_suffix":   dnsSuffixVal,
			"enabled":      v.Enabled,
			"extra_routes": extraRoutes,
			"split_tunnel": v.SplitTunnel,
			"use_mxedge":   v.UseMxedge,
		})

	return objVal, diags
}

func (v IpsecValue) Equal(o attr.Value) bool {
	other, ok := o.(IpsecValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DnsServers.Equal(other.DnsServers) {
		return false
	}

	if !v.DnsSuffix.Equal(other.DnsSuffix) {
		return false
	}

	if !v.Enabled.Equal(other.Enabled) {
		return false
	}

	if !v.ExtraRoutes.Equal(other.ExtraRoutes) {
		return false
	}

	if !v.SplitTunnel.Equal(other.SplitTunnel) {
		return false
	}

	if !v.UseMxedge.Equal(other.UseMxedge) {
		return false
	}

	return true
}

func (v IpsecValue) Type(ctx context.Context) attr.Type {
	return IpsecType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IpsecValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"dns_servers": basetypes.ListType{
			ElemType: types.StringType,
		},
		"dns_suffix": basetypes.ListType{
			ElemType: types.StringType,
		},
		"enabled": basetypes.BoolType{},
		"extra_routes": basetypes.ListType{
			ElemType: ExtraRoutesValue{}.Type(ctx),
		},
		"split_tunnel": basetypes.BoolType{},
		"use_mxedge":   basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = ExtraRoutesType{}

type ExtraRoutesType struct {
	basetypes.ObjectType
}

func (t ExtraRoutesType) Equal(o attr.Type) bool {
	other, ok := o.(ExtraRoutesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ExtraRoutesType) String() string {
	return "ExtraRoutesType"
}

func (t ExtraRoutesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	destAttribute, ok := attributes["dest"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dest is missing from object`)

		return nil, diags
	}

	destVal, ok := destAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dest expected to be basetypes.StringValue, was: %T`, destAttribute))
	}

	nextHopAttribute, ok := attributes["next_hop"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`next_hop is missing from object`)

		return nil, diags
	}

	nextHopVal, ok := nextHopAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`next_hop expected to be basetypes.StringValue, was: %T`, nextHopAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ExtraRoutesValue{
		Dest:    destVal,
		NextHop: nextHopVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewExtraRoutesValueNull() ExtraRoutesValue {
	return ExtraRoutesValue{
		state: attr.ValueStateNull,
	}
}

func NewExtraRoutesValueUnknown() ExtraRoutesValue {
	return ExtraRoutesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewExtraRoutesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ExtraRoutesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ExtraRoutesValue Attribute Value",
				"While creating a ExtraRoutesValue value, a missing attribute value was detected. "+
					"A ExtraRoutesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExtraRoutesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ExtraRoutesValue Attribute Type",
				"While creating a ExtraRoutesValue value, an invalid attribute value was detected. "+
					"A ExtraRoutesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExtraRoutesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ExtraRoutesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ExtraRoutesValue Attribute Value",
				"While creating a ExtraRoutesValue value, an extra attribute value was detected. "+
					"A ExtraRoutesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ExtraRoutesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewExtraRoutesValueUnknown(), diags
	}

	destAttribute, ok := attributes["dest"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`dest is missing from object`)

		return NewExtraRoutesValueUnknown(), diags
	}

	destVal, ok := destAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`dest expected to be basetypes.StringValue, was: %T`, destAttribute))
	}

	nextHopAttribute, ok := attributes["next_hop"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`next_hop is missing from object`)

		return NewExtraRoutesValueUnknown(), diags
	}

	nextHopVal, ok := nextHopAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`next_hop expected to be basetypes.StringValue, was: %T`, nextHopAttribute))
	}

	if diags.HasError() {
		return NewExtraRoutesValueUnknown(), diags
	}

	return ExtraRoutesValue{
		Dest:    destVal,
		NextHop: nextHopVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewExtraRoutesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ExtraRoutesValue {
	object, diags := NewExtraRoutesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewExtraRoutesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ExtraRoutesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewExtraRoutesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewExtraRoutesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewExtraRoutesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewExtraRoutesValueMust(ExtraRoutesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ExtraRoutesType) ValueType(ctx context.Context) attr.Value {
	return ExtraRoutesValue{}
}

var _ basetypes.ObjectValuable = ExtraRoutesValue{}

type ExtraRoutesValue struct {
	Dest    basetypes.StringValue `tfsdk:"dest"`
	NextHop basetypes.StringValue `tfsdk:"next_hop"`
	state   attr.ValueState
}

func (v ExtraRoutesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["dest"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["next_hop"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Dest.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["dest"] = val

		val, err = v.NextHop.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["next_hop"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ExtraRoutesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ExtraRoutesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ExtraRoutesValue) String() string {
	return "ExtraRoutesValue"
}

func (v ExtraRoutesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"dest":     basetypes.StringType{},
		"next_hop": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"dest":     v.Dest,
			"next_hop": v.NextHop,
		})

	return objVal, diags
}

func (v ExtraRoutesValue) Equal(o attr.Value) bool {
	other, ok := o.(ExtraRoutesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Dest.Equal(other.Dest) {
		return false
	}

	if !v.NextHop.Equal(other.NextHop) {
		return false
	}

	return true
}

func (v ExtraRoutesValue) Type(ctx context.Context) attr.Type {
	return ExtraRoutesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ExtraRoutesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"dest":     basetypes.StringType{},
		"next_hop": basetypes.StringType{},
	}
}
