// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_org_sso_metadata

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OrgSsoMetadataDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"acs_url": schema.StringAttribute{
				Computed:            true,
				Description:         "If `idp_type`==`saml`",
				MarkdownDescription: "If `idp_type`==`saml`",
			},
			"entity_id": schema.StringAttribute{
				Computed:            true,
				Description:         "If `idp_type`==`saml`",
				MarkdownDescription: "If `idp_type`==`saml`",
			},
			"logout_url": schema.StringAttribute{
				Computed:            true,
				Description:         "If `idp_type`==`saml`",
				MarkdownDescription: "If `idp_type`==`saml`",
			},
			"metadata": schema.StringAttribute{
				Computed:            true,
				Description:         "If `idp_type`==`saml`",
				MarkdownDescription: "If `idp_type`==`saml`",
			},
			"org_id": schema.StringAttribute{
				Required: true,
			},
			"scim_base_url": schema.StringAttribute{
				Computed:            true,
				Description:         "If `idp_type`==`oauth` and `scim_enabled`==`true`",
				MarkdownDescription: "If `idp_type`==`oauth` and `scim_enabled`==`true`",
			},
			"sso_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type OrgSsoMetadataModel struct {
	AcsUrl      types.String `tfsdk:"acs_url"`
	EntityId    types.String `tfsdk:"entity_id"`
	LogoutUrl   types.String `tfsdk:"logout_url"`
	Metadata    types.String `tfsdk:"metadata"`
	OrgId       types.String `tfsdk:"org_id"`
	ScimBaseUrl types.String `tfsdk:"scim_base_url"`
	SsoId       types.String `tfsdk:"sso_id"`
}
