package provider

type SiteWlanModel struct {
	AcctImmediateUpdate                  *bool                    `hcl:"acct_immediate_update"`
	AcctInterimInterval                  *int64                   `hcl:"acct_interim_interval"`
	AcctServers                          []AcctServersValue       `hcl:"acct_servers"`
	Airwatch                             *AirwatchValue           `hcl:"airwatch"`
	AllowIpv6Ndp                         *bool                    `hcl:"allow_ipv6_ndp"`
	AllowMdns                            *bool                    `hcl:"allow_mdns"`
	AllowSsdp                            *bool                    `hcl:"allow_ssdp"`
	ApIds                                []string                 `hcl:"ap_ids"`
	AppLimit                             *AppLimitValue           `hcl:"app_limit"`
	AppQos                               *AppQosValue             `hcl:"app_qos"`
	ApplyTo                              *string                  `hcl:"apply_to"`
	ArpFilter                            *bool                    `hcl:"arp_filter"`
	Auth                                 *AuthValue               `hcl:"auth"`
	AuthServerSelection                  *string                  `hcl:"auth_server_selection"`
	AuthServers                          []AuthServersValue       `hcl:"auth_servers"`
	AuthServersNasId                     *string                  `hcl:"auth_servers_nas_id"`
	AuthServersNasIp                     *string                  `hcl:"auth_servers_nas_ip"`
	AuthServersRetries                   *int64                   `hcl:"auth_servers_retries"`
	AuthServersTimeout                   *int64                   `hcl:"auth_servers_timeout"`
	BandSteer                            *bool                    `hcl:"band_steer"`
	BandSteerForceBand5                  *bool                    `hcl:"band_steer_force_band5"`
	Bands                                []string                 `hcl:"bands"`
	BlockBlacklistClients                *bool                    `hcl:"block_blacklist_clients"`
	Bonjour                              *BonjourValue            `hcl:"bonjour"`
	CiscoCwa                             *CiscoCwaValue           `hcl:"cisco_cwa"`
	ClientLimitDown                      *int64                   `hcl:"client_limit_down"`
	ClientLimitDownEnabled               *bool                    `hcl:"client_limit_down_enabled"`
	ClientLimitUp                        *int64                   `hcl:"client_limit_up"`
	ClientLimitUpEnabled                 *bool                    `hcl:"client_limit_up_enabled"`
	CoaServers                           []CoaServersValue        `hcl:"coa_servers"`
	Disable11ax                          *bool                    `hcl:"disable_11ax"`
	DisableHtVhtRates                    *bool                    `hcl:"disable_ht_vht_rates"`
	DisableUapsd                         *bool                    `hcl:"disable_uapsd"`
	DisableV1RoamNotify                  *bool                    `hcl:"disable_v1_roam_notify"`
	DisableV2RoamNotify                  *bool                    `hcl:"disable_v2_roam_notify"`
	DisableWhenGatewayUnreachable        *bool                    `hcl:"disable_when_gateway_unreachable"`
	DisableWhenMxtunnelDown              *bool                    `hcl:"disable_when_mxtunnel_down"`
	DisableWmm                           *bool                    `hcl:"disable_wmm"`
	DnsServerRewrite                     *DnsServerRewriteValue   `hcl:"dns_server_rewrite"`
	Dtim                                 *int64                   `hcl:"dtim"`
	DynamicPsk                           *DynamicPskValue         `hcl:"dynamic_psk"`
	DynamicVlan                          *DynamicVlanValue        `hcl:"dynamic_vlan"`
	EnableLocalKeycaching                *bool                    `hcl:"enable_local_keycaching"`
	EnableWirelessBridging               *bool                    `hcl:"enable_wireless_bridging"`
	EnableWirelessBridgingDhcpTracking   *bool                    `hcl:"enable_wireless_bridging_dhcp_tracking"`
	Enabled                              *bool                    `hcl:"enabled"`
	FastDot1xTimers                      *bool                    `hcl:"fast_dot1x_timers"`
	HideSsid                             *bool                    `hcl:"hide_ssid"`
	HostnameIe                           *bool                    `hcl:"hostname_ie"`
	Hotspot20                            *Hotspot20Value          `hcl:"hotspot20"`
	InjectDhcpOption82                   *InjectDhcpOption82Value `hcl:"inject_dhcp_option_82"`
	Interface                            *string                  `hcl:"interface"`
	Isolation                            *bool                    `hcl:"isolation"`
	L2Isolation                          *bool                    `hcl:"l2_isolation"`
	LegacyOverds                         *bool                    `hcl:"legacy_overds"`
	LimitBcast                           *bool                    `hcl:"limit_bcast"`
	LimitProbeResponse                   *bool                    `hcl:"limit_probe_response"`
	MaxIdletime                          *int64                   `hcl:"max_idletime"`
	MaxNumClients                        *int64                   `hcl:"max_num_clients"`
	MistNac                              *MistNacValue            `hcl:"mist_nac"`
	MxtunnelIds                          []string                 `hcl:"mxtunnel_ids"`
	MxtunnelName                         []string                 `hcl:"mxtunnel_name"`
	NoStaticDns                          *bool                    `hcl:"no_static_dns"`
	NoStaticIp                           *bool                    `hcl:"no_static_ip"`
	Portal                               *PortalValue             `hcl:"portal"`
	PortalAllowedHostnames               []string                 `hcl:"portal_allowed_hostnames"`
	PortalAllowedSubnets                 []string                 `hcl:"portal_allowed_subnets"`
	PortalDeniedHostnames                []string                 `hcl:"portal_denied_hostnames"`
	Qos                                  *QosValue                `hcl:"qos"`
	Radsec                               *RadsecValue             `hcl:"radsec"`
	Rateset                              map[string]RatesetValue  `hcl:"rateset"`
	ReconnectClientsWhenRoamingMxcluster *bool                    `hcl:"reconnect_clients_when_roaming_mxcluster"`
	RoamMode                             *string                  `hcl:"roam_mode"`
	Schedule                             *ScheduleValue           `hcl:"schedule"`
	SiteId                               string                   `hcl:"site_id"`
	SleExcluded                          *bool                    `hcl:"sle_excluded"`
	Ssid                                 string                   `hcl:"ssid"`
	UseEapolV1                           *bool                    `hcl:"use_eapol_v1"`
	VlanEnabled                          *bool                    `hcl:"vlan_enabled"`
	VlanId                               *string                  `hcl:"vlan_id"`
	VlanIds                              []string                 `hcl:"vlan_ids"`
	VlanPooling                          *bool                    `hcl:"vlan_pooling"`
	WlanLimitDown                        *int64                   `hcl:"wlan_limit_down"`
	WlanLimitDownEnabled                 *bool                    `hcl:"wlan_limit_down_enabled"`
	WlanLimitUp                          *int64                   `hcl:"wlan_limit_up"`
	WlanLimitUpEnabled                   *bool                    `hcl:"wlan_limit_up_enabled"`
	WxtagIds                             []string                 `hcl:"wxtag_ids"`
	WxtunnelId                           *string                  `hcl:"wxtunnel_id"`
	WxtunnelRemoteId                     *string                  `hcl:"wxtunnel_remote_id"`
}
